# Generated by Django 3.2.8 on 2021-10-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userdetails_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
