# Generated by Django 3.2.8 on 2021-11-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userdetails_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='company',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='cover_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='education',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='rank_star',
            field=models.IntegerField(default=0),
        ),
    ]
