# Generated by Django 3.1.7 on 2021-12-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211207_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solutionCode',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='problem',
            name='templateSolutionCode',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
