# Generated by Django 3.1.7 on 2021-12-27 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20211208_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_code', models.CharField(max_length=10000)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('submission_language', models.CharField(max_length=100)),
                ('submission_score', models.IntegerField(default=0)),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.problem')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
