# Generated by Django 3.1.7 on 2022-01-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='country',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='programming_languages',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='skills',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
