# Generated by Django 3.1.7 on 2022-01-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220104_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='descriptionImage',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
